### ISSUE TITLE
Calculation explanation?

### ISSUE THREAD

**Issue by henry74** [sharkbait-au/HRV_iq#1]
Hi @sharkbait-au thanks for open sourcing your code.  Can you explain where you found the calculation for the HRV score?

I'm referring specifically to this line in HRVApp.mc:
```
hrv = ((Math.log(rmssd, 1.0512712)) + 0.5).toNumber();
```
Everywhere I've read, they are using the natural log of rmssd.  
Thanks!

**Comment by keskparane** [comment]
As I understood it at the time the natural log formula had been patented. So I calculated a formula that would return results that were comparable without using the patented formula. I choose to make the results comparable because I considered the output to be an accepted standard in HRV monitoring.

**Comment by sharkbait-au** [comment]
As I understood it at the time the natural log formula had been patented. So I calculated a formula that would return results that were comparable without using the patented formula. I choose to make the results comparable because I considered the output to be an accepted standard in HRV monitoring.

**Comment by henry74** [comment]
I've tried using the natural log:
```
hrv = Math.ln(rmssd).toNumber() 
```
and the number is between 0 and 1 so doesn't seem to be the same thing.  Is there another factor or calculation I'm missing to get to an HRV score between 0 and 100?

**Comment by sharkbait-au** [comment]
hrv = (20 * Math.ln(rmssd)).toNumber()

**Comment by henry74** [comment]
Thanks
